CREATE TABLE CLIENT_MASTER (CLIENT_NO VARCHAR(6), NAME VARCHAR(20),ADDRESS1 VARCHAR(30),ADDRESS2 VARCHAR(30),CITY VARCHAR(15),STATE VARCHAR(15),PINCODE NUMBER(6,0),BAL_DUE NUMBER(10,2) );



CREATE TABLE PRODUCT_MASTER (PRODUCT_NO VARCHAR(6), DESCRIPTION VARCHAR(15),PROFIT_PERCENT NUMBER(4,2),UNIT_MEASURE VARCHAR(10),QTY_ON_HAND NUMBER(8,0),RECORDER_LVL NUMBER(8,0),SELL_PRICE NUMBER(8,2),COST_PRICE NUMBER(8,2) );
