CREATE TABLE CLIENT_MASTER (CLIENT_NO VARCHAR(6), NAME VARCHAR(20),ADDRESS1 VARCHAR(30),ADDRESS2 VARCHAR(30),CITY VARCHAR(15),STATE VARCHAR(15),PINCODE NUMBER(6,0),BAL_DUE NUMBER(10,2) );



CREATE TABLE PRODUCT_MASTER (PRODUCT_NO VARCHAR(6), DESCRIPTION VARCHAR(15),PROFIT_PERCENT NUMBER(4,2),UNIT_MEASURE VARCHAR(10),QTY_ON_HAND NUMBER(8,0),RECORDER_LVL NUMBER(8,0),SELL_PRICE NUMBER(8,2),COST_PRICE NUMBER(8,2) );


--INSERT INTO CLIENT_MASTER (&CLIENT_NO,&NAME,&ADDRESS1,&ADDRESS2,&CITY,&STATE,&PINCODE,&BAL_DUE); 
--
--INSERT
--INTO client_master (CLIENT_NO,NAME ,ADDRESS1 ,ADDRESS2 ,CITY ,STATE ,PINCODE ,BAL_DUE) VALUES
--('0003','Pramada','C/2','nariman','Bombay','Maharashtra',400057,5000)

--SELECT * FROM client_master

INSERT INTO client_master (client_no,NAME,ADDRESS1,ADDRESS2,CITY,STATE,PINCODE,BAL_DUE) VALUES (&a,&b,&c,&d,&e,&f,&g,&h)
