select * from CLIENT_MASTER where CITY LIKE '_a%';
select * from CLIENT_MASTER where NAME like '_a%';
select name from CLIENT_MASTER where city like 'M%';
select * from PRODUCT_MASTER ORDER BY DESCRIPTION ;
select COUNT(*) from PRODUCT_MASTER;
SELECT AVG(SELL_PRICE) FROM PRODUCT_MASTER ;
SELECT MIN(SELL_PRICE) FROM PRODUCT_MASTER ;
SELECT MAX(SELL_PRICE) AS max_price,MIN(SELL_PRICE) AS min_price FROM PRODUCT_MASTER ;
SELECT COUNT(*) FROM PRODUCT_MASTER WHERE SELL_PRICE >= 1500;
