select * from CLIENT_MASTER where CITY LIKE '_a%';
select * from CLIENT_MASTER where NAME like '_a%';
select name from CLIENT_MASTER where city like 'M%';
select * from PRODUCT_MASTER ORDER BY DESCRIPTION ;
select COUNT(*) from PRODUCT_MASTER;
SELECT AVG(SELL_PRICE) FROM PRODUCT_MASTER ;
SELECT MIN(SELL_PRICE) FROM PRODUCT_MASTER ;
SELECT MAX(SELL_PRICE) AS max_price,MIN(SELL_PRICE) AS min_price FROM PRODUCT_MASTER ;
SELECT COUNT(*) FROM PRODUCT_MASTER WHERE SELL_PRICE >= 1500;



---extra
SELECT NAME,dept_name from INSTRUCTOR;
SELECT DISTINCT dept_name from INSTRUCTOR;
SELECT name from INSTRUCTOR where DEPT_NAME='Comp. Sci.' and SALARY>70000;
select name,INSTRUCTOR.DEPT_NAME,building from INSTRUCTOR,DEPARTMENT where DEPARTMENT.DEPT_NAME=INSTRUCTOR.DEPT_NAME ;
select INSTRUCTOR.NAME,COURSE.TITLE , COURSE.COURSE_ID from INSTRUCTOR,COURSE,TEACHES WHERE TEACHES.COURSE_ID=COURSE.COURSE_ID AND TEACHES.ID=INSTRUCTOR.ID;
select INSTRUCTOR.NAME,COURSE.TITLE , COURSE.COURSE_ID,INSTRUCTOR.DEPT_NAME from INSTRUCTOR,COURSE,TEACHES WHERE TEACHES.COURSE_ID=COURSE.COURSE_ID AND TEACHES.ID=INSTRUCTOR.ID AND INSTRUCTOR.DEPT_NAME='Comp. Sci.';
SELECT NAME FROM INSTRUCTOR WHERE SALARY > ANY(SELECT SALARY FROM INSTRUCTOR WHERE DEPT_NAME='Biology');
SELECT DEPT_NAME FROM DEPARTMENT WHERE BUILDING LIKE '%Watson%';
select * from INSTRUCTOR where DEPT_NAME='Physics' ORDER BY SALARY DESC;
select * from INSTRUCTOR ORDER BY SALARY desc,name;
select * from INSTRUCTOR where SALARY >90000 and SALARY<100000;
